language: cpp
compiler: gcc
dist: trusty
sudo: true

install: 
  - sudo apt-get install libpthread-stubs0-dev libglc-dev pxlib-dev libxrandr-dev 
libfreetype6-dev libglew-dev libjpeg-dev libsndfile1-dev libopenal-dev
  - sudo apt-get install libbox2d-dev --yes

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - ./build.sh
